### ISSUE TITLE
Consensus genomes from "custom" python script

### ISSUE THREAD

**Issue by danagibbon** [alexcritschristoph/wastewater_sarscov2#1]
Hi Alex,

Thanks for posting your code that goes along with your paper! It is very helpful.
In your methods you mentioned that: "Consensus genomes from each sample were created using a custom Python script that required a minimum of three reads supporting each genomic position."
I was wondering if that script is in this repo? I am curious on how you created your consensus genomes.

Thanks!

**Comment by alexcritschristoph** [comment]
Hi,
I have posted the script used here for reference:
https://gist.github.com/alexcritschristoph/db5f33fa6e319d7f76b890bbd6fe2dc8

However, you might want to try a different approach for that, like assembly in geneious - there are also some other programs out there that can do this sort of reference-aligned assembly but I'm not too experienced in them. Good luck!
Alex

**Comment by danagibbon** [comment]
Thank you, Alex!
