### ISSUE TITLE
Linkage function in inStrain

### ISSUE THREAD

**Issue by cswift3** [alexcritschristoph/wastewater_sarscov2#2]
Hi,
Thanks for making your code available to support your paper!
I am curious why the linkage function in inStrain was not used in the wastewater data analysis (at least that I could tell). I was thinking that this might be a good way to tell if two SNVs were present on the same read and thus from the same SARS-CoV-2 genome.

Thanks,
Candice

**Comment by alexcritschristoph** [comment]
Hi Candice,
That's a really good idea! Honestly we didn't have the time or space in our work to do that kind of analysis. The only issue that I'm thinking about is that many key SNPs are quite far apart on the SARS-CoV-2 genome, so read linkage might be somewhat limited. But in theory it should work!
Alex

**Comment by cswift3** [comment]
Makes sense, thanks for the feedback!

Candice
